services:
  postgres:
    container_name: auth_postgres
    image: postgres
    restart: on-failure
    ports:
      - 4001:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    volumes:
      - data:/etc/data/postgres/auth_postgres


volumes:
  data: