services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6001:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./data:/data
  postgres:
    container_name: messages_postgres
    image: postgres
    restart: on-failure
    ports:
      - 4002:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messages
    volumes:
      - data:/etc/data/postgres/messages_postgres


volumes:
  data: