services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6000:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./data:/data
  postgres:
    container_name: posts_postgres
    image: postgres
    restart: on-failure
    ports:
      - 4004:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: posts
    volumes:
      - data:/etc/data/postgres/posts_postgres


volumes:
  data: