port: 3002
env: local
services:
  authAddr: localhost:3001
db:
  port: 4002
  host: localhost
  password: postgres
  user: postgres
  name: messages
broker:
  addr: localhost:29092
  topic: UpdateOnline