services:
  postgres:
    container_name: user_postgres
    image: postgres
    restart: on-failure
    ports:
      - 4001:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    volumes:
      - data:/etc/data/postgres/user_postgres


volumes:
  data: